// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package weichhart.georg.communication;

public final class CommunicationServices {
  private CommunicationServices() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\017Weichhart.Georg\032\rmessa" +
      "ge.proto\032\016resource.proto2R\n\016ResourceStat" +
      "us\022@\n\tGetStatus\022\030.Weichhart.Georg.Messag" +
      "e\032\031.Weichhart.Georg.Resource2R\n\rStatusCh" +
      "anged\022A\n\013StatusEvent\022\030.Weichhart.Georg.M" +
      "essage\032\030.Weichhart.Georg.MessageB9\n\035weic" +
      "hhart.georg.communicationB\025Communication" +
      "Services\210\001\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          weichhart.georg.communication.PerformativeMessages.getDescriptor(),
          weichhart.georg.communication.ResourceMessages.getDescriptor(),
        });
    weichhart.georg.communication.PerformativeMessages.getDescriptor();
    weichhart.georg.communication.ResourceMessages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
